### PR TITLE
Vaadin layout integration.

### PR DESCRIPTION
**Pull request by juliocri**
This branch adds the vaadin layout in index.html

### CODE REVIEW

**Comment by jketreno** [comment]
@juliocri This is looking great!

Two additions to get into this branch and then we can merge it to master:

1. Does vaadin-split-layout support sending the iron-resize notification?  If so, we can add the iron resize behavior in board-viewer to call it's onResize handler and dynamically resize the board based on the viewport.

2. Can you add a patch that fixes the heights of the two vertical vaadin split layouts to the page height so they then scroll their content instead of expanding to fit the content panel?

In the following image, the left panel would then have a scroll bar and on the right, the document view would have a scroll bar instead of a body scrollbar:

image

**Comment by juliocri** [comment]
@jketreno  point 1 is now available, :) now working in point 2.

**Review by jketreno — CHANGES_REQUESTED** [review]
Functionality is spot on.

Looking at the patch, I started thinking we could move the resize behavior code into the board-viewer element itself since it looks like vaadin-split-layout participates in the IronResizeBehavior.

So I tested a (quick hack) modified version of your patch that put all iron-resize-behavior logic in board-viewer itself, which will then allow that component to do the "right thing" whenever embedded within a Polymer application.

So--can you move these changes into the ```<board-viewer>```  and have the iron-resize listener in that element call onResize it can simplify the work of those trying to use the component?

We should also rename board-viewer's "onResize" to "resize" and have it be part of the public API for the component so that when it is wrapped in Angular, that framework can call resize() directly when it needs the contents to resize.

**Comment by juliocri** [comment]
@jketreno point 2 was solved. :)

**Pull request merged**
